services:
  - type: web
    name: shubhkart-server
    env: node
    plan: free
    rootDir: ./Server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromDatabase:
          name: shubhkart-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: shubhkart-client
    env: static
    plan: free
    rootDir: ./Client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: REACT_APP_API_URL
        value: https://your-server-url.onrender.com

databases:
  - name: shubhkart-db
    plan: free